### ISSUE TITLE
不显示光标问题

### ISSUE THREAD

**Issue by BoykinChoi** [zhuxu1/CityPicker#1]
你好。请教一下，不显示光标问题具体修改了哪里呢？

**Comment by zhuxu1** [comment]
好像是颜色问题吧.. 好像原来的颜色是白色啊还是怎么着来着，具体忘记了。找到cp_search_view.xml下的cp_search_box，属性textCursorDrawable，修改里面的shape_cursor_edt就可以了

**Comment by BoykinChoi** [comment]
@zhuxu1  谢谢哈。问题解决了，的确是textCursorDrawable，原版里自定义主题时 <item name="cpSearchCursorDrawable">@color/color_green</item> 。这里应该是设置drawable。自定义一个shape_cursor_edt 设置成 <item name="cpSearchCursorDrawable">@drawable/shape_cursor_edt</item> 就可以了。
由于现在需求还比较简单，所以没用到你的版本，还是感谢哈！
